### ISSUE TITLE
Readme的二维码扫描出来是404哦

### ISSUE THREAD

**Issue by Mulsd** [CofbroTeam/Doraemon#102]
> ## 🖱️ 使用
>目前项目还处于开发阶段，如果您想尝鲜已开发的功能或者迫切需要使用签到功能，请在 `issue` 中告诉我们。
>### 1. 链接
>[尝鲜版请前往 releases](https://github.com/CofbroTeam/Doraemon/releases)。由于项目处于开发阶段，并且我们没有测试同学，因此如果大家在使用过程中遇到 `bug`，或者对本项目有更好的 `需求和建议`，烦请在 `issue` 中提出，一起让 Doraemon 更加完善。
>### 2. QR-Code
>请使用浏览器或手机自带的二维码扫描器扫描。
><div> <img src="https://github.com/CofbroTeam/Doraemon/assets/101956946/60125d13-97d2-4515-a3e4-6460ac97c9d0" width = 200 height = 200 /> </div>
↑↑这个哦

**Comment by cofbro** [comment]
加群获取最新apk吧

**Comment by krrrre** [comment]
> 加群获取最新apk吧

qq群在哪加
