### ISSUE TITLE
登录了几次还是不行，弹出 Toast 就没有任何反应了

### ISSUE THREAD

**Issue by cofbro** [CofbroTeam/Doraemon#11]
登录了几次还是不行，弹出 Toast 就没有任何反应了
系统版本: Android 14

_Originally posted by @XHQ6666 in https://github.com/CofbroTeam/Doraemon/issues/10#issuecomment-1759800442_

**Comment by cofbro** [comment]
> ```
>           登录了几次还是不行，弹出 Toast 就没有任何反应了
> ```
> 
> 系统版本: Android 14
> 
> _Originally posted by @XHQ6666 in [#10 (comment)](https://github.com/CofbroTeam/Doraemon/issues/10#issuecomment-1759800442)_

https://github.com/CofbroTeam/Doraemon/issues/10#issuecomment-1760182337

**Comment by WoAiNianChu** [comment]
> > ```
> >           登录了几次还是不行，弹出 Toast 就没有任何反应了
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 系统版本: Android 14 
> > _最初发布者 @XHQ6666在 [＃10（评论） ](https://github.com/CofbroTeam/Doraemon/issues/10#issuecomment-1759800442)_
> 
> [#10（评论） ](https://github.com/CofbroTeam/Doraemon/issues/10#issuecomment-1760182337)

用的Gboard键盘吧，换个输入法就可以输入了

**Comment by XHQ6666** [comment]
> > > ```
> > >           登录了几次还是不行，弹出 Toast 就没有任何反应了
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 系统版本: Android 14 
> > > _最初发布者 @XHQ6666在 [＃10（评论） ](https://github.com/CofbroTeam/Doraemon/issues/10#issuecomment-1759800442)_
> > 
> > [#10（评论） ](https://github.com/CofbroTeam/Doraemon/issues/10#issuecomment-1760182337)
> 
> 用的Gboard键盘吧，换个输入法就可以输入了

### 并不是，是密码包含特殊字符导致无法登陆，不是无法输入密码
