### ISSUE TITLE
请问这个软件在哪里下载，还有人在开发吗

### ISSUE THREAD

**Issue by HickeyM** [CofbroTeam/Doraemon#119]

**Comment by HickeyM** [comment]
有没有好心人告知如何下载

**Comment by 0721master** [comment]
> QQ群903827851

搜不到这个群

**Comment by GwIhViEte** [comment]
> > QQ群903827851
> 
> 搜不到这个群

![qrcode_1715967709164.jpg](https://github.com/CofbroTeam/Doraemon/assets/135035462/b5cf58ea-9e83-4267-8d36-f8a1a2760c5c)

这样应该可以吧
