### ISSUE TITLE
2024.6.1编译

### ISSUE THREAD

**Issue by Xiao-yux** [CofbroTeam/Doraemon#124]
自己编译的
https://wwf.lanzouv.com/iJm3g20fecdc
密码:1p2n

**Comment by gurain** [comment]
非常感谢🙏

**Comment by zhourx1129** [comment]
大佬，为什么这个没有那个抢答功能啊

**Comment by Xiao-yux** [comment]
> 大佬，为什么这个没有那个抢答功能啊
> 

不知道，没用过这个

**Comment by wcool1** [comment]
大佬，貌似用不了了，一直停在加载课程中
