### ISSUE TITLE
部分手机登录页面中的输入框无法输入

### ISSUE THREAD

**Issue by cofbro** [CofbroTeam/Doraemon#19]
pixels系列，三星自带输入法也有同样问题

**Comment by WoAiNianChu** [comment]
用的Gboard键盘吧，换个输入法就可以输入了

> pixels系列，三星自带输入法也有同样问题

用的Gboard键盘吧，换个输入法就可以输入了

**Comment by cofbro** [comment]
[部分手机输入框无法输入](https://github.com/CofbroTeam/Doraemon/pull/39)
