### ISSUE TITLE
深色模式以及布局问题

### ISSUE THREAD

**Issue by XHQ6666** [CofbroTeam/Doraemon#23]
### 页面未适配深色模式，深色模式下部分文字和图标不可见，另外 App 布局需要注意安全区区域，确保不会被 System UI 覆盖

![Screenshot_2023-10-17-20-47-49-974_com cofbro qian](https://github.com/CofbroTeam/Doraemon/assets/95635323/4d1f0b49-29dd-4753-a344-8607368b8f6c)

**Comment by XHQ6666** [comment]
分辨率 `2400x1080` DPI `420`

**Comment by cofbro** [comment]
您好请问机型是？？

**Comment by cofbro** [comment]
深色模式暂不支持，后期会把这块补上。

**Comment by XHQ6666** [comment]
> 深色模式暂不支持，后期会把这块补上。

好的
