### ISSUE TITLE
位置签到能否根据老师发起的位置自动获取签到位置信息，然后自动填写（位置签到上面显示的内容）

### ISSUE THREAD

**Issue by Moetazhxi** [CofbroTeam/Doraemon#37]
https://github.com/PrintNow/ChaoxingSign

使用这个项目的位置签到时不需要手动填写信息，它可以自动获取位置信息，也就是说位置签到上面显示的内容会自动填写，不需要手动写，这个项目或许可以作为参考（?）

我也不知道我有没有表达清楚（

**Comment by cofbro** [comment]
好的，我们已经收到反馈
