### ISSUE TITLE
位置签到卡在了定位成功，无法签到

### ISSUE THREAD

**Issue by rospod** [CofbroTeam/Doraemon#56]
位置签到直接点击签到一直显示定位成功，不会显示成功签到

**Comment by cofbro** [comment]
您好，请提供图片或视频以及您的手机型号。

**Comment by rospod** [comment]
视频：
https://mateague-my.sharepoint.com/:v:/g/personal/admin_mateague_onmicrosoft_com/EXEYOPF-tDhHkKeG-fdnlvABrzGciU6zhq2NBHk9J8WkYg?e=77qlXH

备注：老师没有提供签到的位置信息（可能是api获取教师签到位置失败了就卡住了）

手机型号：Samsung Galaxy A52
OneUI 3.1 Android 11

cofbro ***@***.***> 于 2023年11月9日周四 14:54写道：

**Comment by rospod** [comment]
上面那个链接如果有问题的话打开这个，onedrive for bussiness的连接有些时候会被吞成emoji
https://suo.yt/wij2aJE

**Comment by cofbro** [comment]
@xxxd86 看下这个

**Comment by xxxd86** [comment]
好的，尽快解决

**Comment by cofbro** [comment]
> 上面那个链接如果有问题的话打开这个，onedrive for bussiness的连接有些时候会被吞成emoji https://suo.yt/wij2aJE

问题已解决。如果老师没有设置位置，请使用搜索位置功能后，再点击签到按钮。
