### ISSUE TITLE
token失效时，自动重新登陆

### ISSUE THREAD

**Issue by NianBroken** [CofbroTeam/Doraemon#59]
在设置增加类似“`保存当前账号及密码`”和“`保存所有账号及密码（主账号和关联账号）`”的选项

若该项设置为打开状态，当检测到账号token失效时，自动根据已保存的账号密码在后台进行登陆
- 若登陆成功，则**不要**向用户提示类似“token失效”等字样，让用户感觉就像是账号没失效一样
- 若登陆失败，则自动弹出登陆界面，并告知用户需重新登陆

**Comment by cofbro** [comment]
功能已上线 - 版本： `DAMX_20240319072211`
