### ISSUE TITLE
关于Workflow的Key

### ISSUE THREAD

**Issue by SummonHIM** [CofbroTeam/Doraemon#88]
Workflow的key是将base64编码之后的key字符串存进secrets。名字叫SIGNING_KEY
```
base64 输入文件
```
运行时才会从secrets里面自动导出
```
      - name: Prepare signing key
        run: echo '${{ secrets.SIGNING_KEY }}' | base64 -d > signingkey.jks
```
实际运行时 serects 相关内容会加*处理的

还有密码是明文存在serects里的
```
          ALIAS: ${{ secrets.ALIAS }}
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
```

最后一点小建议是cos的版本号是固定的。感觉不太灵活。建议上个[变量](https://docs.github.com/en/actions/learn-github-actions/variables)或者echo 变量名=变量>>$GITHUB_ENV 到环境变量里面

**Comment by cofbro** [comment]
```
region: ${{ secrets.COS_REGION }}
          secret-id: ${{ secrets.COS_SECRET_ID }}
          secret-key: ${{ secrets.COS_SECRET_KEY }}
          bucket: ${{ secrets.COS_BUCKET }}
```
把这几个发我吧

**Comment by SummonHIM** [comment]
> ```
> region: ${{ secrets.COS_REGION }}
>           secret-id: ${{ secrets.COS_SECRET_ID }}
>           secret-key: ${{ secrets.COS_SECRET_KEY }}
>           bucket: ${{ secrets.COS_BUCKET }}
> ```
> 
> 把这几个发我吧

这cos这些不是我pr的喔

**Comment by cofbro** [comment]
😂看错了...

**Comment by SummonHIM** [comment]
草🤣
